version: "3.9"
services:
  bd:
    networks:
      - mynet
    image: ncbeltranb/flask-python-db:latest
    ports:
      - "3306:3306"
    container_name: dbalpine
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=contactsflask
    volumes:
      - ./mariadb:/var/lib/mysql
  flask:
    networks:
      - mynet
    image: ncbeltranb/flask-python-app:latest
    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - bd
networks:
  mynet:
    external: true